spring:
  application:
    name: faceapi
  datasource:
    url: jdbc:oracle:thin:@172.20.22.10:1521:orcl
    username: bsits2
    password: bsits2
    driver-class-name: oracle.jdbc.OracleDriver
  output:
    ansi:
      enabled: always
  redis:
    database: 0
    host: localhost
    port: 6379
server:
  port: 8191
mybatis:
  type-aliases-package: com.sailing.facetec.entiry
logging:
  level:
    root: info
  file: logfile.log
eureka:
  client:
    service-url:
      defaultZone: http://172.20.22.11:8181/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
management:
  security:
    enabled: false
info:
  com: sailing
  product: faceapi

tasks:
  capture: 0/1 * * * * ?
  alter: 0/1 * * * * ?

actioncodes:
  SUCCEED_CODE: 1000
  SUCCEED_MSG: 请求成功
  SERVER_ERROR_CODE: 9999
  SERVER_ERROR_MSG: 服务端异常:%s
  PARAMS_ERROR_CODE: 2001
  PARAMS_ERROR_MSG: 参数错误:%s

supplys:
    supply-map:
        yt_rlk_rlkid: rlk.rlkid1
        yt_rl_rlkid: rl.rlkid1
        yt_rl_rlid: rl.rlid1
        hr_rlk_rlkid: rlk.rlkid2
        hr_rl_rlkid: rl.rlkid2
        hr_rl_rlid: rl.rlid2
upload:
  image-folder: D:\
ytface:
  api-url: http://172.20.25.226:11180


