spring:
  application:
    name: faceapi
  datasource:
    url: jdbc:oracle:thin:@172.20.22.10:1521:orcl
    username: bsits2
    password: bsits2
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
server:
  port: 8090
mybatis:
  type-aliases-package: com.sailing.facetec.entiry
logging:
  level:
    root: info
  file: logfile.log


