spring:
  application:
    name: apigateway
server:
  port: 8300
zuul:
  routes:
    - demoapi:
        path: /demoapi/**
        serviceId: demoapi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/