# apigateway 配置
# 2017-05-19

# 应用名称
spring:
  application:
    name: apigateway
  # 输出语法高亮
  output:
    ansi:
      enabled: always
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
# 服务端口
server:
  port: 8183
# 路由设置
zuul:
  routes:
    # faceapi 路由
    - faceapi:
        path: /faceapi/**
        serviceId: faceapidemo
    # 测试服务 demoapi 路由
    - demoapi:
        path: /demoapi/**
        serviceId: demoapi
# erueka 服务中心设置
eureka:
  client:
    # 服务中心地址
    service-url:
      defaultZone: http://localhost:8181/eureka/
    # 开启健康监测
    healthcheck:
      enabled: true
  # 设定心跳时间
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
# 关闭默认转发超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
# 设置管理权限是否需要安全验证 关闭后 可以使用 actuator 查看服务状态
management:
  security:
    enabled: false
# 允许远程关闭
endpoints:
  shutdown:
    enabled: true
    sensitive: false
info:
  com: sailing
  product: ApiGateway