spring:
  application:
    name: apigateway
server:
  port: 8183
zuul:
  routes:
    - faceapi:
        path: /faceapi/**
        serviceId: faceapi
    - demoapi:
        path: /demoapi/**
        serviceId: demoapi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/