spring:
  application:
    name: configserver
  # 使用本地配置文件目录
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/workpath/svn/springclouddemo-dev/ConfigServer/yamls/
  rabbitmq:
    host: localhost
    port: 5672
    username: sailing
    password: sailing
  output:
    ansi:
      enabled: always
# 设置服务端口 8001
server:
  port: 8182
# 设置 EurekaServer 地址 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/
management:
  security:
    enabled: false