spring:
  application:
    name: configserver
  # 使用本地配置文件目录
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/yunan/tools/Services/ConfigServer/yamls/
  rabbitmq:
    host: 172.20.25.45
    port: 5672
    username: sailing
    password: sailing
# 设置服务端口 8001
server:
  port: 8182
# 设置 EurekaServer 地址 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://172.20.22.11:8181/eureka/