spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/workpath/src/springclouddemo-dev/ConfigServer/yamls/
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/