# 设定服务端口 8181
server:
  port: 8181
eureka:
  # EurekaClient 配置
  client:
    # 设定不将自身注册到服务中心
    register-with-eureka: false
    fetch-registry: false
    # 设定EurekaServer 的服务中心地址
    service-url:
      defaultZone: http://0.0.0.0:${server.port}/eureka/
  # 驱逐下线服务的时间 默认是 60s 设定为5s 提供更快的检测
  # 建议生产情况下使用默认值
  server:
    eviction-interval-timer-in-ms: 5000
    # 关闭自我保护
    enable-self-preservation: false
spring:
  # 输出高亮
  output:
    ansi:
      enabled: always
# 设置管理权限是否需要安全验证 关闭后 可以使用 actuator 查看服务状态
management:
  security:
    enabled: false
# 允许远程关闭
endpoints:
  shutdown:
    enabled: true
    sensitive: false