server:
  port: 8102
spring:
  application:
    name: demoapi
  kafka:
    bootstrap-servers: 172.20.22.11:9092
#    bootstrap-servers: 172.20.25.209:9092
    consumer:
      group-id: testyu

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8181/eureka/
#  instance:
#    # 心跳包周期 默认 30s
#    lease-renewal-interval-in-seconds: 5
#    # 距离上一次心跳 15s 后服务下线 默认 90s
#    lease-expiration-duration-in-seconds: 15
management:
  security:
    enabled: false